layout_id = "symbols"
name = "Symbols"

[[keys]]
id = "undo"
shade = "dark"
circle = false
legend = "↺"

[keys.actions.tap]
type = "undo"

[[keys]]
id = "sym_period"
shade = "light"
circle = false
legend = "."

[keys.actions.tap]
type = "text"
text = "."

[keys.actions.left]
type = "text"
text = ":"

[keys.actions.right]
type = "text"
text = ";"

[[keys]]
id = "sym_comma"
shade = "light"
circle = false
legend = ","

[keys.actions.tap]
type = "text"
text = ","

[keys.actions.left]
type = "text"
text = "<"

[keys.actions.right]
type = "text"
text = ">"

[[keys]]
id = "sym_bang"
shade = "light"
circle = false
legend = "!"

[keys.actions.tap]
type = "text"
text = "!"

[keys.actions.left]
type = "text"
text = "~"

[[keys]]
id = "backspace"
shade = "dark"
circle = false
legend = "⌫"

[keys.actions.tap]
type = "backspace"

[[keys]]
id = "emote"
shade = "dark"
circle = false
legend = "☻"

[keys.actions.tap]
type = "emote"

[[keys]]
id = "sym_quote"
shade = "light"
circle = false
legend = "'"

[keys.actions.tap]
type = "text"
text = "'"

[keys.actions.left]
type = "text"
text = "\""

[keys.actions.right]
type = "text"
text = "`"

[[keys]]
id = "sym_at"
shade = "light"
circle = false
legend = "@"

[keys.actions.tap]
type = "text"
text = "@"

[keys.actions.left]
type = "text"
text = "%"

[keys.actions.right]
type = "text"
text = "^"

[[keys]]
id = "sym_amp"
shade = "light"
circle = false
legend = "&"

[keys.actions.tap]
type = "text"
text = "&"

[keys.actions.left]
type = "text"
text = "*"

[[keys]]
id = "settings"
shade = "dark"
circle = false
legend = "⚙"

[keys.actions.tap]
type = "settings"

[[keys]]
id = "shift"
shade = "dark"
circle = false
legend = "⬆"
shift = "⇧"
caps = "⇪"

[keys.actions.tap]
type = "shift"

[[keys]]
id = "sym_dash"
shade = "light"
circle = false
legend = "-"

[keys.actions.tap]
type = "text"
text = "-"

[keys.actions.left]
type = "text"
text = "_"

[keys.actions.right]
type = "text"
text = "+"

[[keys]]
id = "sym_equal"
shade = "light"
circle = false
legend = "="

[keys.actions.tap]
type = "text"
text = "="

[[keys]]
id = "sym_pipe"
shade = "light"
circle = false
legend = "|"

[keys.actions.tap]
type = "text"
text = "|"

[keys.actions.left]
type = "text"
text = "/"

[keys.actions.right]
type = "text"
text = "\\"

[[keys]]
id = "space"
shade = "dark"
circle = false
legend = "␣"

[keys.actions.tap]
type = "space"

[[keys]]
id = "switch"
shade = "dark"
circle = false
legend = "ABC"

[keys.actions.tap]
type = "switch"

[[keys]]
id = "sym_question"
shade = "light"
circle = false
legend = "?"

[keys.actions.tap]
type = "text"
text = "?"

[keys.actions.left]
type = "text"
text = "("

[keys.actions.right]
type = "text"
text = ")"

[[keys]]
id = "sym_hash"
shade = "light"
circle = false
legend = "#"

[keys.actions.tap]
type = "text"
text = "#"

[keys.actions.left]
type = "text"
text = "["

[keys.actions.right]
type = "text"
text = "]"

[[keys]]
id = "sym_dollar"
shade = "light"
circle = false
legend = "$"

[keys.actions.tap]
type = "text"
text = "$"

[keys.actions.left]
type = "text"
text = "{"

[keys.actions.right]
type = "text"
text = "}"

[[keys]]
id = "submit"
shade = "light"
circle = true
submit = true
legend = "⏎"

[keys.actions.tap]
type = "submit"
hold = true